- hosts: localhost
  connection: local
  gather_facts: no           
  become: yes
  become_user: "{{ user }}"

  vars:
    user: "{{ lookup('env', 'USER') }}"

    home_dir: "/Users/{{ user }}"

    anyenv_dir: "{{ home_dir }}/.anyenv"

    homebrew_taps:
      - caskroom/cask
      - caskroom/versions
      - sanemat/font

    homebrew_packages:
      - { name: lua }
      - { name: readline }
      - { name: openssl, state: linked }
      - { name: ansible }
      - { name: colordiff }
      - { name: coreutils }
      - { name: doxygen }
      - { name: gibo }
      - { name: git }
      - { name: git-secrets }
      - { name: graphviz }
      - { name: htop-osx }
      - { name: jq }
      - { name: ricty, install_options: [powerline, vim-powerline] }
      - { name: vim, install_options: [devel, with-lua] }
      - { name: zsh }
      - { name: zsh-completions }
      - { name: zsh-syntax-highlighting }

    homebrew_cask_packages:
      - cheatsheet
      - clion
      - firefox
      - google-chrome
      - intellij-idea
      - java
      - macdown

  tasks:
    # brew tap
    - name: install taps of homebrew
      homebrew_tap: tap="{{ item }}" state=present
      with_items: '{{homebrew_taps}}'

    # update homebrew
    - name: update homebrew
      homebrew: update_homebrew=yes

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: '{{homebrew_packages}}'

    # brew cask install
    - name: update brew-cask
      homebrew: name=brew-cask state=latest
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item }}" state=present
      with_items: '{{homebrew_cask_packages}}'

    # install Ricty font
    - name: install xquartz
      homebrew_cask: name=xquartz
    - name: install ricty
      homebrew: name=ricty
    - name: copy generated font file
      shell: "cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/"
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

    # install anyenv
    - name: install anyenv
      git: repo=https://github.com/riywo/anyenv dest={{ anyenv_dir }} version="master"
    - name: make anyenv plugins directory
      file: path={{ anyenv_dir }}/plugins state=directory
    - name: install anyenv-udpate
      git: repo=https://github.com/znz/anyenv-update.git dest={{ anyenv_dir }}/plugins/anyenv-update version="master"
    - name: install anyenv-git
      git: repo=https://github.com/znz/anyenv-git.git dest={{ anyenv_dir }}/plugins/anyenv-git version="master"

    # install jenv by anyenv
    - name: install jenv by anyenv
      shell: "anyenv install -s jenv"

    # apply anyenv
    - name: apply anyenv
      shell: "exec $SHELL -L"

    # install java by jenv
    - name: jenv add java8
      shell: "jenv add $(/usr/libexec/java_home -v '1.8')"

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
