- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_user: "{{ user }}"
  roles:
    - homebrew-cask
    - homebrew
    # one time
    #- git-secrets
    # one time
    #- homesick
    # one time
    #- ricty-font
    #- vim
    # one time
    #- anyenv

  vars:
    user: "{{ lookup('env', 'USER') }}"
