- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_user: "{{ user }}"
  roles:
    #- homebrew-tap
    - homebrew-cask
    #- homebrew
    #- git-secrets
    #- homesick
    #- ricty-font
    #- vim
    #- anyenv
    #- gem
    #- debug

  vars:
    user: "{{ lookup('env', 'USER') }}"
