- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_user: "{{ user }}"
  roles:
    - homebrew-cask
    - homebrew
    - ricty-font
    - vim
    - anyenv

  vars:
    user: "{{ lookup('env', 'USER') }}"
