---
- name: install anyenv
  git: repo=https://github.com/riywo/anyenv dest={{ anyenv_dir }} version="master"

- name: make anyenv plugins directory
  file: path={{ anyenv_dir }}/plugins state=directory

- name: install anyenv-udpate
  git: repo=https://github.com/znz/anyenv-update.git dest={{ anyenv_dir }}/plugins/anyenv-update version="master"

- name: install anyenv-git
  git: repo=https://github.com/znz/anyenv-git.git dest={{ anyenv_dir }}/plugins/anyenv-git version="master"

- name: install jenv by anyenv
  shell: "anyenv install -s jenv"

- name: install scalaenv by anyenv
  shell: "anyenv install -s scalaenv"

- name: install sbtenv by anyenv
  shell: "anyenv install -s sbtenv"

- name: apply anyenv
  shell: "exec $SHELL -L"

