---
- name: install
  become: yes
  shell: "sudo gem install homesick"

- name: git clone
  shell: "homesick clone git@private.github.com:oyajikun/dotfiles.git"

- name: symlink
  shell: "homesick symlink dotfiles"
